/*
 * Slack API Client
 * This is a Java client for Slack API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import io.slack.api.client.api.TestApi;
import io.slack.api.client.invoker.ApiException;
import io.slack.api.client.model.ApiTestResponse;
import io.slack.api.client.model.EmptyBody;
import org.junit.Test;

/**
 * API tests for TestApi
 */
public class TestApiTest {

    private final TestApi api = new TestApi();

    /**
     * Checks API calling code.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiTestTest() throws ApiException {
        EmptyBody emptyBody = new EmptyBody();
        ApiTestResponse apiTestResponse = api.apiTest(null, null, emptyBody);
        System.out.println(apiTestResponse);
    }
}
